%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Enable)
%;**     @brief
%;**         Enable the device (ACTIVE mode) 
%include Common\GeneralParameters.inc(27)
%;**         @return
%;**         uint8_t %>27 - Error code, ERR_OK if no error. 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
