%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Init)
%;**     @brief
%;**         Initializes the device driver 
%include Common\GeneralParameters.inc(27)
%;**         @return
%;**         uint8_t %>27 - Error code, ERR_OK for no error. 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
