%- AUTOREGENERATE If you remove this line, this file cannot be rewrited (by default)
%ifndef CommentLine
%{
%endif CommentLine
%;** ===================================================================
%include Common\GeneralMethod.inc (Disable)
%;**     @brief
%;**         Put the sensor in Standby mode by clearing the ACTIVE bit in 
%;**         the CTRL register 1. 
%include Common\GeneralParameters.inc(27)
%;**         @return
%;**         uint8_t %>27 - Error code 
%include Common\GeneralDamage.inc
%;** ===================================================================
%ifndef CommentLine
%}
%endif CommentLine
